### ISSUE TITLE
Undefined property: YellowCore::$text in /system/layouts/pagination.html

### ISSUE THREAD

**Issue by IngoBelka** [datenstrom/yellow#567]
Hi,

this comes from the Apache error.log - only the last lines - there are some more of these before:
```
[Thu Nov 26 15:10:04.300383 2020] [php7:notice] [pid 4984] [client 147.61.10.4:54304] PHP Notice:  Undefined property: YellowCore::$text in /var/www/html/kristall/system/layouts/pagination.html on line 8, referer: https://testserver/kristall/edit/sitemap/page:2
[Thu Nov 26 15:10:04.300451 2020] [php7:error] [pid 4984] [client 147.61.10.4:54304] PHP Fatal error:  Uncaught Error: Call to a member function getHtml() on null in /var/www/html/kristall/system/layouts/pagination.html:8\nStack trace:\n#0 /var/www/html/kristall/system/extensions/core.php(684): require()\n#1 /var/www/html/kristall/system/extensions/core.php(349): YellowPage->includeLayout()\n#2 /var/www/html/kristall/system/layouts/sitemap.html(13): YellowCore->layout()\n#3 /var/www/html/kristall/system/extensions/core.php(684): require('/var/www/html/k...')\n#4 /var/www/html/kristall/system/extensions/core.php(666): YellowPage->includeLayout()\n#5 /var/www/html/kristall/system/extensions/core.php(617): YellowPage->parsePageLayout()\n#6 /var/www/html/kristall/system/extensions/core.php(213): YellowPage->parsePage()\n#7 /var/www/html/kristall/system/extensions/core.php(149): YellowCore->sendPage()\n#8 /var/www/html/kristall/system/extensions/edit.php(285): YellowCore->processRequest()\n#9 /var/www/html/kristall/system/extensions/edit.php(248): YellowEdit->processRequestShow()\n#10 /var/www/html/kristall/system/extensions/e in /var/www/html/kristall/system/layouts/pagination.html on line 8, referer: https://testserver/kristall/edit/sitemap/page:2
```
While calling the site index at the and of the page I get this error message:
```
Something went wrong. Please activate debug mode for more information. See troubleshooting. 
```
What do I have to do to solve this?

greetings Ingo

**Comment by IngoBelka** [comment]
I found it ... 

The update did not touch pagination.html.

**Comment by markseu** [comment]
Good to hear you already solved the error message.  👍

Hope it's okay to ask a question. In the recent weeks we had some cases were the logging didn't work as expected. Was the `system/extensions/yellow.log` more helpful this time and pointed you to the right direction?

**Comment by IngoBelka** [comment]
Hi Mark,
for sure it's always ok, to ask questions. 
These are the the last lines of yellow.log:
```
2020-11-17 07:42:22 info Update extension 'Berlin 0.8.10'
2020-11-17 07:42:22 info Update extension 'Blog 0.8.12'
2020-11-17 07:42:22 info Update extension 'Bundle 0.8.17'
2020-11-17 07:42:22 info Update extension 'Command 0.8.25'
2020-11-17 07:42:22 info Update extension 'Core 0.8.31'
2020-11-17 07:42:22 info Update extension 'Edit 0.8.39'
2020-11-17 07:42:22 info Update extension 'English 0.8.25'
2020-11-17 07:42:22 info Update extension 'French 0.8.25'
2020-11-17 07:42:22 info Update extension 'Gallery 0.8.10'
2020-11-17 07:42:22 info Update extension 'German 0.8.25'
2020-11-17 07:42:22 info Update extension 'Image 0.8.11'
2020-11-17 07:42:22 info Update extension 'Markdown 0.8.16'
2020-11-17 07:42:22 info Update extension 'Search 0.8.11'
2020-11-17 07:42:22 info Update extension 'Update 0.8.43'
2020-11-17 07:42:22 info Update extension 'Wiki 0.8.13'
2020-11-17 07:42:30 info Convert settings files
2020-11-24 05:42:26 info Update extension 'Bundle 0.8.18'
2020-11-24 05:42:26 info Update extension 'Core 0.8.34'
2020-11-24 05:42:26 info Update extension 'Image 0.8.12'
2020-11-24 05:42:26 info Update extension 'Update 0.8.45'
2020-11-24 05:42:33 info Update Datenstrom Yellow 0.8.16, PHP 7.4.3, Apache 2.4.41, Linux
2020-11-24 13:16:50 error Can't parse file 'system/layouts/pagination.html'!
2020-11-24 14:54:25 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 10:30:28 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 10:32:12 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 10:43:28 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 10:44:22 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 10:45:05 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 12:07:50 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 12:09:32 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 12:48:23 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 13:12:19 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 13:17:20 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 13:18:48 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 13:29:04 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 13:42:27 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 13:53:51 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 14:03:07 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 14:09:36 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 14:09:51 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 14:10:04 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 14:21:37 error Can't parse file 'system/layouts/pagination.html'!
2020-11-26 14:33:15 error Can't parse file 'system/layouts/pagination.html'!
```
But the Apache log file had more detailed information. And the last posts here pointed me to compare my local and the file at the git repository. So I found out that the update did process all files except pagination.html.

Is it this, what you wanted to know?

**Comment by markseu** [comment]
Lovely, this is exactly what I wanted to know. 😁

You can show more detailed information. If you're not 100% sure what causes problems, I would [activate the debug mode](https://datenstrom.se/yellow/help/troubleshooting#problems-after-update). This will do two things. First activate PHP's `display_errors` on your web server. Secondly tell Datenstrom Yellow to show exactly what's going on on the current page. If have a local web server for development, I would [always display errors](https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display).

**Comment by IngoBelka** [comment]
Good to know that, thank you. I'm working with Yellow just for 3 month seriously and so I'm getting more familiar with Yellow, while learning by doing. I have a local virtual machine for development, indeed. :thumbsup:

**Comment by markseu** [comment]
![This is the way](https://user-images.githubusercontent.com/2429165/100379065-960f5b00-3014-11eb-8950-18eb97e3c4ba.jpg)
